app/views/misc_views.py
# Copyright 2014 SolidBuilds.com. All rights reserved
#
# Authors: Ling Thio <ling.thio@gmail.com>


from flask import Blueprint, redirect, render_template
from flask import request, url_for
from flask_user import current_user, login_required, roles_accepted

from app import db
from app.models.user_models import UserProfileForm

# When using a Flask app factory we must use a blueprint to avoid needing 'app' for '@app.route'
main_blueprint = Blueprint('main', __name__, template_folder='templates')

# The Home page is accessible to anyone
@main_blueprint.route('/')
def home_page():
    return render_template('pages/home_page.html')


# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/member')
@login_required  # Limits access to authenticated users
def member_page():
    return render_template('pages/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_accepted('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('pages/admin_page.html')


@main_blueprint.route('/pages/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.home_page'))

    # Process GET or invalid POST
    return render_template('pages/user_profile_page.html',
                           form=form)

app/templates/pages/admin_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
    <h2>{%trans%}Admin Page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

app/templates/pages/home_page.html
{% extends "common/page_base.html" %}

{% block content %}
    <h2>{%trans%}Home page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

app/templates/pages/user_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
    <h2>{%trans%}Members page{%endtrans%}</h2>
    <p><a href={{ url_for('user.register') }}>{%trans%}Register{%endtrans%}</a></p>
    <p><a href={{ url_for('user.login') }}>{%trans%}Sign in{%endtrans%}</a></p>
    <p><a href={{ url_for('main.home_page') }}>{%trans%}Home Page{%endtrans%}</a> (accessible to anyone)</p>
    <p><a href={{ url_for('main.member_page') }}>{%trans%}Member Page{%endtrans%}</a> (login_required: member@example.com / Password1)</p>
    <p><a href={{ url_for('main.admin_page') }}>{%trans%}Admin Page{%endtrans%}</a> (roles_required: admin@example.com / Password1)</p>
    <p><a href={{ url_for('user.logout') }}>{%trans%}Sign out{%endtrans%}</a></p>
{% endblock %}

app/templates/pages/user_profile_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>User Profile</h1>

<p><a href="{{ url_for('user.change_password') }}">Change password</a></p>

{% from "common/form_macros.html" import render_field, render_submit_field %}
<form action="" method="POST" class="form" role="form">
  <div class="row">
    <div class="col-sm-6 col-md-5 col-lg-4">
    {{ form.hidden_tag() }}

    {{ render_field(form.first_name, tabindex=240) }}

    {{ render_field(form.last_name, tabindex=250) }}

    {{ render_submit_field(form.submit, tabindex=280) }}
    </div>
  </div>
</form>

{% endblock %}